/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Order IT Youth – Admin API
 * Admin API for managing catalog, combos, orders and payments for the Order IT Youth charity store.
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

/**
 * @nullable
 */
export type ProductVariantDtoOption1 = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProductVariantDtoOption2 = { [key: string]: unknown } | null;

export interface ProductVariantDto {
  id: string;
  sku: string;
  option1?: ProductVariantDtoOption1;
  option2?: ProductVariantDtoOption2;
  price_vnd: number;
  price_version: number;
  stock: number;
}

/**
 * @nullable
 */
export type ProductResponseDtoDescription = { [key: string]: unknown } | null;

export interface ProductResponseDto {
  id: string;
  name: string;
  description?: ProductResponseDtoDescription;
  is_donation_item: boolean;
  variants: ProductVariantDto[];
}

/**
 * @nullable
 */
export type ComboComponentVariantDtoOption1 = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ComboComponentVariantDtoOption2 = { [key: string]: unknown } | null;

export interface ComboComponentVariantDto {
  id: string;
  sku: string;
  option1?: ComboComponentVariantDtoOption1;
  option2?: ComboComponentVariantDtoOption2;
  price_vnd: number;
  price_version: number;
}

export interface ComboComponentDto {
  variant: ComboComponentVariantDto;
  quantity: number;
}

export type ComboResponseDtoPricingType =
  (typeof ComboResponseDtoPricingType)[keyof typeof ComboResponseDtoPricingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComboResponseDtoPricingType = {
  FIXED_PRICE: 'FIXED_PRICE',
  SUM_COMPONENTS: 'SUM_COMPONENTS',
  SUM_MINUS_AMOUNT: 'SUM_MINUS_AMOUNT',
  SUM_MINUS_PERCENT: 'SUM_MINUS_PERCENT',
} as const;

export interface ComboResponseDto {
  id: string;
  name: string;
  slug: string;
  pricing_type: ComboResponseDtoPricingType;
  list_price_vnd: number;
  amount_off_vnd: number;
  percent_off: number;
  price_version: number;
  components: ComboComponentDto[];
}

export interface CheckoutItemDto {
  /**
   * @description ID của biến thể sản phẩm, chỉ truyền nếu item là variant.
   */
  variant_id?: string;
  /**
   * @description ID của combo, chỉ truyền nếu item là combo.
   */
  combo_id?: string;
  quantity: number;
  /**
   * @description Version giá mà FE lưu, dùng để kiểm tra lệch giá.
   */
  price_version: number;
  /**
   * @description Đơn giá mà FE đang hiển thị, dùng để thông báo chi tiết khi giá thay đổi.
   */
  client_price_vnd?: number;
}

export type CheckoutOrderDtoFulfillmentType =
  (typeof CheckoutOrderDtoFulfillmentType)[keyof typeof CheckoutOrderDtoFulfillmentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckoutOrderDtoFulfillmentType = {
  DELIVERY: 'DELIVERY',
  PICKUP_SCHOOL: 'PICKUP_SCHOOL',
} as const;

export type CheckoutOrderDtoPaymentMethod =
  (typeof CheckoutOrderDtoPaymentMethod)[keyof typeof CheckoutOrderDtoPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckoutOrderDtoPaymentMethod = {
  VIETQR: 'VIETQR',
  CASH: 'CASH',
  MANUAL_TRANSFER: 'MANUAL_TRANSFER',
} as const;

export interface CheckoutOrderDto {
  full_name: string;
  /**
   * @description Số điện thoại khách hàng.
   */
  phone: string;
  email?: string;
  address?: string;
  note?: string;
  fulfillment_type?: CheckoutOrderDtoFulfillmentType;
  payment_method?: CheckoutOrderDtoPaymentMethod;
  /**
   * @description Mã coupon nếu có.
   */
  coupon_code?: string;
  /**
   * @description Scope để đảm bảo idempotent (ví dụ checkout:session-abc).
   */
  idem_scope: string;
  /**
   * @description Key duy nhất trong scope, thường là UUID.
   */
  idem_key: string;
  items: CheckoutItemDto[];
}

/**
 * @nullable
 */
export type OrderItemResponseDtoVariantId = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type OrderItemResponseDtoComboId = { [key: string]: unknown } | null;

export interface OrderItemResponseDto {
  title: string;
  variant_id?: OrderItemResponseDtoVariantId;
  combo_id?: OrderItemResponseDtoComboId;
  unit_price_vnd: number;
  quantity: number;
  line_total_vnd: number;
}

export type OrderResponseDtoFulfillmentType =
  (typeof OrderResponseDtoFulfillmentType)[keyof typeof OrderResponseDtoFulfillmentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDtoFulfillmentType = {
  DELIVERY: 'DELIVERY',
  PICKUP_SCHOOL: 'PICKUP_SCHOOL',
} as const;

export type OrderResponseDtoPaymentMethod =
  (typeof OrderResponseDtoPaymentMethod)[keyof typeof OrderResponseDtoPaymentMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDtoPaymentMethod = {
  VIETQR: 'VIETQR',
  CASH: 'CASH',
  MANUAL_TRANSFER: 'MANUAL_TRANSFER',
} as const;

export type OrderResponseDtoPaymentStatus =
  (typeof OrderResponseDtoPaymentStatus)[keyof typeof OrderResponseDtoPaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDtoPaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

/**
 * High-level lifecycle status for the order (CREATED → PAID → FULFILLING → DELIVERY_FAILED → FULFILLED → CANCELLED).
 */
export type OrderResponseDtoOrderStatus =
  (typeof OrderResponseDtoOrderStatus)[keyof typeof OrderResponseDtoOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderResponseDtoOrderStatus = {
  CREATED: 'CREATED',
  PAID: 'PAID',
  FULFILLING: 'FULFILLING',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
} as const;

export interface OrderResponseDto {
  code: string;
  full_name: string;
  phone: string;
  fulfillment_type: OrderResponseDtoFulfillmentType;
  payment_method: OrderResponseDtoPaymentMethod;
  payment_status: OrderResponseDtoPaymentStatus;
  /**
   * @description High-level lifecycle status for the order (CREATED → PAID → FULFILLING → DELIVERY_FAILED → FULFILLED → CANCELLED).
   */
  order_status: OrderResponseDtoOrderStatus;
  /**
   * @description Number of delivery attempts recorded so far.
   */
  delivery_attempts: number;
  /**
   * @description Timestamp when the last delivery attempt failed.
   */
  delivery_failed_at?: string;
  /**
   * @description Recorded reason for the last failed delivery attempt.
   */
  delivery_failed_reason?: string;
  /**
   * @description Timestamp when the order was fulfilled.
   */
  fulfilled_at?: string;
  /**
   * @description Timestamp when the order was cancelled.
   */
  cancelled_at?: string;
  /**
   * @description Recorded reason for cancellation.
   */
  cancelled_reason?: string;
  grand_total_vnd: number;
  items: OrderItemResponseDto[];
}

/**
 * Optional extra details.
 */
export type ErrorResponseDtoDetails = { [key: string]: unknown };

export interface ErrorResponseDto {
  error_code: string;
  message: string;
  /**
   * @description Optional extra details.
   */
  details?: ErrorResponseDtoDetails;
}

export interface PaymentIntentBankDto {
  bank_code: string;
  account_no: string;
  account_name: string;
}

export type PaymentIntentResponseDtoPaymentStatus =
  (typeof PaymentIntentResponseDtoPaymentStatus)[keyof typeof PaymentIntentResponseDtoPaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentIntentResponseDtoPaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export interface PaymentIntentResponseDto {
  order_code: string;
  payment_status: PaymentIntentResponseDtoPaymentStatus;
  amount_vnd: number;
  transfer_content: string;
  bank: PaymentIntentBankDto;
}

export interface ConfirmPaymentDto {
  /**
   * @description Order code cần confirm thanh toán.
   */
  order_code: string;
  /**
   * @description Số tiền đã nhận thực tế (VND).
   */
  amount_vnd: number;
  /**
   * @description Transaction ID duy nhất từ sao kê ngân hàng.
   */
  transaction_id: string;
  /**
   * @description Tham chiếu nội bộ, mặc định = order_code.
   */
  reference_code?: string;
  /**
   * @description Ghi chú/raw reference note từ sao kê.
   */
  reference_note?: string;
  /**
   * @description Thời điểm thanh toán dạng ISO 8601. Mặc định là thời điểm gọi API.
   */
  paid_at?: string;
  /**
   * @description Đặt true để cho phép force dù lệch số tiền.
   */
  force?: boolean;
  /**
   * @description Lý do đi kèm khi phải force confirm.
   */
  reason?: string;
}

/**
 * Payment status after confirmation.
 */
export type PaymentRecordDtoPaymentStatus =
  (typeof PaymentRecordDtoPaymentStatus)[keyof typeof PaymentRecordDtoPaymentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentRecordDtoPaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export interface PaymentRecordDto {
  /**
   * @description Indicates the confirmation succeeded.
   */
  ok: boolean;
  /**
   * @description Code of the order whose payment was confirmed.
   */
  order_code: string;
  /**
   * @description Payment status after confirmation.
   */
  payment_status: PaymentRecordDtoPaymentStatus;
}

/**
 * Payload thô (JSON) từ import hoặc webhook.
 */
export type ManualCreateBankTransactionDtoRaw = { [key: string]: unknown };

export interface ManualCreateBankTransactionDto {
  /**
   * @description Số tiền giao dịch (VND).
   */
  amount_vnd: number;
  /**
   * @description Thời điểm giao dịch theo ISO 8601. FE sẽ convert “15:32 30/11/2025” sang ISO string trước khi gửi.
   */
  occurred_at: string;
  /**
   * @description Transaction ID duy nhất từ sao kê.
   */
  transaction_id: string;
  /**
   * @description Mô tả/narrative trong sao kê.
   */
  narrative: string;
  /**
   * @description Order code nếu admin đã xác định trước.
   */
  matched_order_code?: string;
  /**
   * @description Payload thô (JSON) từ import hoặc webhook.
   */
  raw?: ManualCreateBankTransactionDtoRaw;
}

export interface AdminCreateVariantDto {
  /**
   * @description Unique SKU within the product.
   */
  sku: string;
  /**
   * @description First option such as size.
   */
  option1?: string;
  /**
   * @description Second option such as color.
   */
  option2?: string;
  /**
   * @description Price in VND.
   */
  priceVnd: number;
  /**
   * @description Available stock quantity.
   */
  stock: number;
}

export interface AdminCreateProductDto {
  /**
   * @description Product display name.
   */
  name: string;
  /**
   * @description Detailed description of the product.
   */
  description?: string;
  /**
   * @description Mark true if this product is a donation item.
   */
  isDonationItem?: boolean;
  /**
   * @description Initial variants to create with the product.
   */
  variants?: AdminCreateVariantDto[];
  /**
   * @description Main image URL of the product stored after upload.
   */
  readonly imageUrl?: string;
}

export interface AdminUpdateProductDto {
  /**
   * @description Updated product name.
   */
  name?: string;
  /**
   * @description Updated description.
   */
  description?: string;
  /**
   * @description Updated donation flag.
   */
  isDonationItem?: boolean;
  /**
   * @description Main image URL of the product stored after upload.
   */
  readonly imageUrl?: string;
}

export interface AdminUpdateVariantDto {
  /**
   * @description Updated SKU value.
   */
  sku?: string;
  /**
   * @description Updated option1
   */
  option1?: string;
  /**
   * @description Updated option2
   */
  option2?: string;
  /**
   * @description Updated price
   */
  priceVnd?: number;
  /**
   * @description Updated stock
   */
  stock?: number;
}

export interface AdminComboComponentDto {
  /**
   * @description Variant ID participating in the combo.
   */
  variantId: string;
  /**
   * @description Quantity of the variant in the combo.
   */
  quantity: number;
  /**
   * @description Override unit price for this variant when part of the combo.
   */
  unitPriceOverrideVnd?: number;
}

/**
 * Pricing strategy for the combo.
 */
export type AdminCreateComboDtoPricingType =
  (typeof AdminCreateComboDtoPricingType)[keyof typeof AdminCreateComboDtoPricingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCreateComboDtoPricingType = {
  FIXED_PRICE: 'FIXED_PRICE',
  SUM_COMPONENTS: 'SUM_COMPONENTS',
  SUM_MINUS_AMOUNT: 'SUM_MINUS_AMOUNT',
  SUM_MINUS_PERCENT: 'SUM_MINUS_PERCENT',
} as const;

export interface AdminCreateComboDto {
  /**
   * @description Display name of the combo.
   */
  name: string;
  /**
   * @description Unique slug for the combo.
   */
  slug: string;
  /**
   * @description Combo description shown to customers.
   */
  description?: string;
  /**
   * @description Pricing strategy for the combo.
   */
  pricingType: AdminCreateComboDtoPricingType;
  /**
   * @description List price used for FIXED_PRICE combos.
   */
  listPriceVnd: number;
  /**
   * @description Amount discount for SUM_MINUS_AMOUNT combos.
   */
  amountOffVnd?: number;
  /**
   * @description Percent discount for SUM_MINUS_PERCENT combos.
   */
  percentOff?: number;
  /**
   * @description Whether the combo is active for purchase.
   */
  isActive?: boolean;
  /**
   * @description Optional cover image URL.
   */
  coverImage?: string;
  /**
   * @description Components that make up the combo.
   */
  components: AdminComboComponentDto[];
  /**
   * @description Cover image URL stored after upload.
   */
  readonly coverImageUrl?: string;
}

/**
 * Updated pricing type.
 */
export type AdminUpdateComboDtoPricingType =
  (typeof AdminUpdateComboDtoPricingType)[keyof typeof AdminUpdateComboDtoPricingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdateComboDtoPricingType = {
  FIXED_PRICE: 'FIXED_PRICE',
  SUM_COMPONENTS: 'SUM_COMPONENTS',
  SUM_MINUS_AMOUNT: 'SUM_MINUS_AMOUNT',
  SUM_MINUS_PERCENT: 'SUM_MINUS_PERCENT',
} as const;

export interface AdminUpdateComboDto {
  /**
   * @description Updated combo name.
   */
  name?: string;
  /**
   * @description Updated slug.
   */
  slug?: string;
  /**
   * @description Updated description.
   */
  description?: string;
  /**
   * @description Updated pricing type.
   */
  pricingType?: AdminUpdateComboDtoPricingType;
  /**
   * @description Updated list price.
   */
  listPriceVnd?: number;
  /**
   * @description Updated amount discount.
   */
  amountOffVnd?: number;
  /**
   * @description Updated percent discount.
   */
  percentOff?: number;
  /**
   * @description Updated active flag.
   */
  isActive?: boolean;
  /**
   * @description Updated cover image URL.
   */
  coverImage?: string;
  /**
   * @description Replacing combo components.
   */
  components?: AdminComboComponentDto[];
  /**
   * @description Cover image URL stored after upload.
   */
  readonly coverImageUrl?: string;
}

export interface ProviderPayloadDto {
  /**
   * @description Reference note or memo captured from the bank statement.
   */
  referenceNote?: string;
}

export interface AdminConfirmPaymentDto {
  /**
   * @description Amount received in VND.
   */
  amountVnd: number;
  /**
   * @description Unique transaction reference code.
   */
  transactionId?: string;
  /**
   * @description Force confirm even when amount mismatch.
   */
  force?: boolean;
  /**
   * @description Timestamp when payment was made.
   */
  paidAt?: string;
  /**
   * @description Provider payload metadata, e.g. reference note.
   */
  providerPayload?: ProviderPayloadDto;
}

export interface AdminStartFulfilmentDto {
  /**
   * @description Optional note for the fulfilment task.
   */
  note?: string;
}

/**
 * Reason code for the failed delivery attempt.
 */
export type AdminFailFulfilmentDtoReasonCode =
  (typeof AdminFailFulfilmentDtoReasonCode)[keyof typeof AdminFailFulfilmentDtoReasonCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminFailFulfilmentDtoReasonCode = {
  CUSTOMER_NO_SHOW: 'CUSTOMER_NO_SHOW',
  UNREACHABLE: 'UNREACHABLE',
  WRONG_LOCATION: 'WRONG_LOCATION',
  OTHER: 'OTHER',
} as const;

export interface AdminFailFulfilmentDto {
  /**
   * @description Reason code for the failed delivery attempt.
   */
  reason_code: AdminFailFulfilmentDtoReasonCode;
  /**
   * @description Additional notes about the failure.
   */
  note?: string;
}

export interface AdminRetryFulfilmentDto {
  /**
   * @description Optional note for the retry attempt.
   */
  note?: string;
}

export interface AdminCompleteFulfilmentDto {
  /**
   * @description Optional timestamp for when fulfilment completed.
   */
  fulfilled_at?: string;
  /**
   * @description Optional summary note for the completion.
   */
  note?: string;
}

export interface AdminCancelOrderDto {
  /**
   * @description Reason for cancellation.
   */
  reason: string;
}

export const getOrderITYouthAdminAPI = () => {
  /**
   * @summary Khởi tạo checkout công khai
   */
  const ordersControllerCheckout = <TData = AxiosResponse<OrderResponseDto>>(
    checkoutOrderDto: CheckoutOrderDto,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(`/api/orders/checkout`, checkoutOrderDto, options);
  };

  /**
   * @summary Lấy thông tin thanh toán VietQR
   */
  const ordersControllerGetPaymentIntent = <
    TData = AxiosResponse<PaymentIntentResponseDto>,
  >(
    code: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`/api/orders/${code}/payment-intent`, options);
  };

  return { ordersControllerCheckout, ordersControllerGetPaymentIntent };
};
export type OrdersControllerCheckoutResult = AxiosResponse<OrderResponseDto>;
export type OrdersControllerGetPaymentIntentResult =
  AxiosResponse<PaymentIntentResponseDto>;
